pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'sudo apt-get update'
                sh 'sudo apt-get -y install python3-pip'
            }
        }

        stage('run') {
            steps {
                sh 'python3 s05/python-simple-app/app.py &'
            }
        }

        stage('test') {
            steps {
                sh 'sleep 60 && curl -s localhost:8000'
            }
        }

        stage('cleanup') {
            steps {
                sh 'fuser -k 8000/tcp'
            }
        }

    }
}
